package com.enflame.happy.domain.model

/**
 * Data extracted from a QR code during the pairing process.
 *
 * The QR code generated by the CLI contains the device's public key
 * encoded as base64, along with optional metadata about the CLI instance.
 *
 * The public key is used for X25519 key agreement to establish
 * end-to-end encrypted communication between the Android client and CLI.
 */
data class PairingData(
    /** Base64-encoded public key from the CLI device. */
    val publicKey: String,
    /** Optional display name of the CLI device/machine. */
    val deviceName: String? = null,
    /** Platform identifier (e.g., "macos", "linux", "windows"). */
    val platform: String? = null,
    /** CLI app version string. */
    val appVersion: String? = null
)
