nodeLinker: node-modules
enableImmutableInstalls: false

# Suppress peer dependency warnings that are safe to ignore
# - YN0060: lottie-react-native@7.x declares @lottiefiles/dotlottie-react@^0.13.5 but works with 0.17.x
# - YN0086: Generic "some peer deps incorrectly met by dependencies" (transitive deps, informational only)
logFilters:
  - code: YN0060
    pattern: "@lottiefiles/dotlottie-react*"
    level: discard
  - code: YN0086
    level: discard