#!/bin/bash
#
# Download PWA screenshots from Cloudflare Worker to local public/screenshots/
#
# Usage:
#   ./download-screenshots.sh [dev|prod]
#
# This script fetches screenshots generated by the Browser Rendering worker
# and saves them to the Vue app's public/screenshots/ directory.
#
# @see HAP-923 - Create PWA screenshot assets for install prompt

set -e

ENV="${1:-dev}"
OUTPUT_DIR="../../public/screenshots"

if [ "$ENV" = "prod" ]; then
  BASE_URL="https://happy-pwa-screenshots.enflamemedia.workers.dev"
else
  BASE_URL="https://happy-pwa-screenshots-dev.enflamemedia.workers.dev"
fi

echo ""
echo "🖼️  Downloading PWA Screenshots"
echo "   Environment: $ENV"
echo "   Source: $BASE_URL"
echo "   Output: $OUTPUT_DIR"
echo ""

# Create output directory if it doesn't exist
mkdir -p "$OUTPUT_DIR"

# Screenshots to download
SCREENSHOTS=("desktop-home.png" "mobile-home.png")

# Check status first
echo "Checking screenshot status..."
STATUS=$(curl -s "$BASE_URL/status")
COMPLETE=$(echo "$STATUS" | grep -o '"complete":[^,]*' | cut -d':' -f2)

if [ "$COMPLETE" != "true" ]; then
  echo ""
  echo "⚠️  Screenshots not yet generated. Run generation first:"
  echo "   curl $BASE_URL/generate"
  echo ""
  echo "Current status:"
  echo "$STATUS" | jq '.' 2>/dev/null || echo "$STATUS"
  exit 1
fi

# Download each screenshot
for SCREENSHOT in "${SCREENSHOTS[@]}"; do
  echo "Downloading $SCREENSHOT..."
  curl -s "$BASE_URL/screenshot/$SCREENSHOT" -o "$OUTPUT_DIR/$SCREENSHOT"

  # Verify file was downloaded
  if [ -f "$OUTPUT_DIR/$SCREENSHOT" ]; then
    SIZE=$(du -h "$OUTPUT_DIR/$SCREENSHOT" | cut -f1)
    echo "  ✓ $SCREENSHOT ($SIZE)"
  else
    echo "  ✗ Failed to download $SCREENSHOT"
    exit 1
  fi
done

echo ""
echo "✅ All screenshots downloaded successfully!"
echo ""
echo "Files:"
ls -la "$OUTPUT_DIR"/*.png
echo ""
