//
//  QRCodePayload.swift
//  Happy
//
//  Created by Happy Engineering
//  Copyright (c) 2024-2026 Enflame Media. All rights reserved.
//

import Foundation

/// Represents the parsed content from a QR code scanned during device pairing.
///
/// The QR code generated by the CLI contains a JSON payload with the CLI's
/// public key and server URL, enabling the mobile app to establish an
/// encrypted connection.
///
/// Expected QR code format (JSON):
/// ```json
/// {
///   "publicKey": "<base64-encoded-public-key>",
///   "serverUrl": "https://...",
///   "machineId": "<optional-machine-id>"
/// }
/// ```
struct QRCodePayload: Codable, Equatable {
    /// The CLI's public key (base64-encoded) used for key exchange.
    let publicKey: String

    /// The server URL the CLI is connected to.
    let serverUrl: String

    /// Optional identifier for the CLI machine.
    let machineId: String?

    // MARK: - Parsing

    /// Parses a raw QR code string into a `QRCodePayload`.
    ///
    /// - Parameter rawValue: The raw string content from the QR code.
    /// - Returns: A parsed `QRCodePayload` if the string is valid JSON with required fields.
    /// - Throws: `QRCodePayloadError` if parsing fails.
    static func parse(from rawValue: String) throws -> QRCodePayload {
        guard let data = rawValue.data(using: .utf8) else {
            throw QRCodePayloadError.invalidEncoding
        }

        let decoder = JSONDecoder()

        do {
            let payload = try decoder.decode(QRCodePayload.self, from: data)

            // Validate required fields are not empty
            guard !payload.publicKey.isEmpty else {
                throw QRCodePayloadError.missingPublicKey
            }

            guard !payload.serverUrl.isEmpty else {
                throw QRCodePayloadError.missingServerUrl
            }

            // Validate the public key is valid base64
            guard Data(base64Encoded: payload.publicKey) != nil else {
                throw QRCodePayloadError.invalidPublicKey
            }

            // Validate the server URL format
            guard URL(string: payload.serverUrl) != nil else {
                throw QRCodePayloadError.invalidServerUrl
            }

            return payload
        } catch let error as QRCodePayloadError {
            throw error
        } catch {
            throw QRCodePayloadError.invalidFormat(underlying: error)
        }
    }
}

// MARK: - Errors

/// Errors that can occur when parsing a QR code payload.
enum QRCodePayloadError: LocalizedError, Equatable {
    /// The raw string could not be decoded as UTF-8.
    case invalidEncoding

    /// The QR code content is not valid JSON or missing required fields.
    case invalidFormat(underlying: Error)

    /// The `publicKey` field is missing or empty.
    case missingPublicKey

    /// The `serverUrl` field is missing or empty.
    case missingServerUrl

    /// The `publicKey` field is not valid base64.
    case invalidPublicKey

    /// The `serverUrl` field is not a valid URL.
    case invalidServerUrl

    var errorDescription: String? {
        switch self {
        case .invalidEncoding:
            return "QR code content could not be read."
        case .invalidFormat:
            return "QR code does not contain valid pairing data."
        case .missingPublicKey:
            return "QR code is missing the public key."
        case .missingServerUrl:
            return "QR code is missing the server URL."
        case .invalidPublicKey:
            return "QR code contains an invalid public key."
        case .invalidServerUrl:
            return "QR code contains an invalid server URL."
        }
    }

    // MARK: - Equatable

    static func == (lhs: QRCodePayloadError, rhs: QRCodePayloadError) -> Bool {
        switch (lhs, rhs) {
        case (.invalidEncoding, .invalidEncoding),
             (.missingPublicKey, .missingPublicKey),
             (.missingServerUrl, .missingServerUrl),
             (.invalidPublicKey, .invalidPublicKey),
             (.invalidServerUrl, .invalidServerUrl):
            return true
        case (.invalidFormat, .invalidFormat):
            return true
        default:
            return false
        }
    }
}
