/**
 * Type declarations for Cloudflare Workers static asset handling
 */

/**
 * The static content manifest is auto-generated by Wrangler when using [site] config.
 * It contains a JSON mapping of asset paths to content hashes for cache invalidation.
 */
declare module '__STATIC_CONTENT_MANIFEST' {
    const manifest: string;
    export default manifest;
}
